#!/usr/bin/env python

import subprocess
from os import system
from sys import argv, exit

# List of nodes in play
nodes_list = ['haproxy', 'master', 'node1']

# Get user argument, will accept only the one, the first one
try:
    operation = (str(argv[1]))
except:
    print('Need one argument. What do you want to do?\n')
    print('E.g: ./cluster status      # To give vagrant status')
    print('     ./cluster up          # To bring up cluster')
    print('     ./cluster halt        # To shutdown gracefully')

# Define functions
def cluster_status():
    cmd = subprocess.run(['vagrant', operation])

def cluster_up_or_down():
    for node in nodes_list:
        cmd = subprocess.run(['vagrant', operation, node])

# Main entry
if operation == 'status':
    cluster_status()
elif operation == 'up' or operation == 'halt':
    cluster_up_or_down()
else:
    print(f"EXIT: { operation } is unknown operation")
