#!/usr/bin/env python

import subprocess
from os import system
from sys import argv, exit

# List of nodes in play
nodes_list = ['haproxy', 'master', 'node1']
run = 'vagrant'

# Define functions
def usage():
    print('Need one argument. What do you want to do?\n')
    print('E.g: ./cluster status      # To give vagrant status')
    print('     ./cluster up          # To bring up cluster')
    print('     ./cluster halt        # To shutdown gracefully')
    exit(1)

def cluster_status():
    cmd = subprocess.run([run, operation])

def cluster_up_or_halt():
    for node in nodes_list:
        cmd = subprocess.run([run, operation, node])

# Main entry
try:
    operation = (str(argv[1]).lower())
except:
    usage()

if operation == 'status':
    cluster_status()
elif operation == 'up' or operation == 'halt':
    cluster_up_or_halt()
else:
    print(f'EXIT: { operation } is unknown operation')
