#!/bin/bash

# Global vars and includes
readonly OS_FAMILY=$(uname)
source provisioning/vars.sh

function check_sudo() {
[[ $UID != 0 ]] && {
 echo "The script wants to make changes to the host. It requires sudo to run ...";
 echo "USAGE: sudo $0 $*";
 exit 1;
 }
}
function configure_dns() {
[[ $OS_FAMILY =~ ^Darwin ]] && sed -i '' "/${FQDN}/d" /etc/hosts || sed -i "/${FQDN}/d" /etc/hosts
echo "172.42.42.10 ${FQDN}" >> /etc/hosts
(($? != 0)) && {
  echo "Something went wrong when writing to /etc/hosts. Aborting";
  exit 1;
  }
echo "DNS Configured. Cluster is ready!"
}
function configure_website_ingress() {
local WEBSITE_KUBE="../website/kubes/ingress.yaml"
[[ ${OS_FAMILY} =~ ^Darwin ]] && sed -i '' "s/configure.me/${FQDN}/" ${WEBSITE_KUBE} || sed -i "s/configure.me/${FQDN}/" ${WEBSITE_KUBE}
}
function main() {
  check_sudo
  configure_dns
  configure_website_ingress
}

main
