# Infrastructure As A Code

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  # NFS Server as an actor of 'Cloud' storage
  config.vm.define "nfs" do |nfs|
    nfs.vm.box = "centos/7"
    nfs.vm.hostname = "storage.barjaktarov.local"
    nfs.vm.network "private_network", ip: "172.42.42.20"
    nfs.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.name = "storage"
      v.memory = 256
      v.cpus = 1
    end
    nfs.vm.provision "shell", path: "provisioning/storage.sh"
  end

  # HAProxy as a Load Balancer for Bare Metal K8s Cluster
  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.box = "centos/7"
    haproxy.vm.hostname = "Loadbalancer.barjaktarov.local"
    haproxy.vm.network "private_network", ip: "172.42.42.10"
    haproxy.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.name = "loadbalancer"
      v.memory = 256
      v.cpus = 1
    end
    haproxy.vm.provision "shell", path: "provisioning/loadbalancer.sh"
  end

  # Kubernetes Master Server
  config.vm.define "master" do |master|
    master.vm.box = "centos/7"
    master.vm.hostname = "master.barjaktarov.local"
    master.vm.network "private_network", ip: "172.42.42.100"
    master.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.name = "master"
      v.memory = 2048
      v.cpus = 2
    end
    master.vm.provision "shell", path: "provisioning/bootstrap.sh"
    master.vm.provision "shell", path: "provisioning/bootstrap_master.sh"
  end

  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "node#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "node#{i}.barjaktarov.local"
      workernode.vm.network "private_network", ip: "172.42.42.10#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--audio", "none"]
        v.name = "node#{i}"
        v.memory = 1500
        v.cpus = 1
      end
      workernode.vm.provision "shell", path: "provisioning/bootstrap.sh"
      workernode.vm.provision "shell", path: "provisioning/bootstrap_nodes.sh"
    end
  end

end
