#!/bin/bash
source ../infrastructure/ansible/vars.sh

function info() {
echo -e "\nWhat do you want me to do, Tear down or Deploy?\n"
echo -e "USAGE: ${YELLOW}./deployment --teardown${RESET}    # To tear down the whole thing (deployment, SERVICES and ingress)"
echo -e "       ${YELLOW}./deployment --deploy${RESET}      # To deploy application the whole thing\n"
}

function tearDown() {
local SERVICES=(wordpress wordpress-mysql)
local PVCS=(mysql-pvc-claim www-pvc-claim)
local START=`date +%s`
echo -e "\n${BLUE}Tearing Down everything ...${RESET}\n"
for KUBE in "${SERVICES[@]}"
 do kubectl delete svc ${KUBE} --now
     kubectl delete deployment ${KUBE} --now
done
kubectl delete ingress wordpress --now
kubectl delete secret mysql-pass --now
for PVC in "${PVCS[@]}"
 do kubectl delete pvc ${PVC} --now
done
local END=`date +%s`
echo -e "\n${WHITE}DONE! Time spent on Tearing Down everything was $((END-START)) second(s)\n"
}

function deploy() {
local COMPONENTS=(secret.yaml service.yaml pvc.yaml ingress.yaml deployment.yaml)
local START=`date +%s`
echo -e "\n${BLUE}Deploying everything ...${RESET}\n"
for OBJECT in "${COMPONENTS[@]}"
 do kubectl create -f kubes/${OBJECT}
done
local END=`date +%s`
echo -e "\n${WHITE}DONE! Time spent on deploying everything was $((END-START)) second(s)\n"
}

function main() {
  [ $# -eq 0 ] && {
  info;
  exit 1;
}
case $1 in
  --teardown)
  tearDown
  exit 0
  ;;
  --deploy)
  deploy
  exit 0
  ;;
  *)
  info
  ;;
esac
  exit 0
}

main $1
