#!/bin/bash

# Declare vars
readonly services=(wordpress wordpress-mysql)
readonly pvcs=(mysql-pvc-claim www-pvc-claim)
readonly k8_pv_location="../components/persistent-volumes"
readonly components=(secret.yaml service.yaml pvc.yaml ingress.yaml deployment.yaml)

function info() {
echo -e "\nWhat do you want me to do, Tear down or Deploy?\n"
echo -e "USAGE: \033[1;33m./deployment --teardown\033[0m    # To tear down the whole thing (deployment, services and ingress)"
echo -e "       \033[1;33m./deployment --deploy\033[0m      # To deploy application the whole thing\n"
}

function tear_down() {
local start=`date +%s`
echo -e "\n\033[1;34mTearing Down everything ...\033[0m\n"
for kube in "${services[@]}"
 do kubectl delete svc ${kube} --now
     kubectl delete deployment ${kube} --now
done
kubectl delete ingress wordpress --now
kubectl delete secret mysql-pass --now
for pvc in "${pvcs[@]}"
 do kubectl delete pvc ${pvc} --now
done
local end=`date +%s`
echo -e "\n\033[1;37mDONE! Time spent on Tearing Down everything was $((end-start)) second(s)\n"
}

function deploy() {
local start=`date +%s`
echo -e "\n\033[1;34mDeploying everything ...\033[0m\n"
for object in "${components[@]}"
 do kubectl create -f kubes/${object}
done
local end=`date +%s`
echo -e "\n\033[1;37mDONE! Time spent on deploying everything was $((end-start)) second(s)\n"
}

function main() {
  [ $# -eq 0 ] && {
  info;
  exit 1;
}
case $1 in
  --teardown)
  tear_down
  exit 0
  ;;
  --deploy)
  deploy
  exit 0
  ;;
  *)
  info
  ;;
esac
  exit 0
}

main $1
